### ISSUE TITLE
dist/index.js is not a ES module

### ISSUE THREAD

**Issue by arlac77** [tamino-martinius/node-github-graphql-api#1]
When trying to import github-graphql-api as ESM
```js
import { GitHub } from 'github-graphql-api';
```

i get the following (rollup error)
```
[!] Error: 'GitHub' is not exported by node_modules/github-graphql-api/dist/index.js
```

```json
{

 "module": "./dist/index.js",
  "name": "github-graphql-api"

}
```

shouldn't the content of dist/index.js be a ESM module ?
Looks like it is a common JS module.

**Comment by tamino-martinius** [comment]
The export is a transpiled-ESM (__esModule) to be compatible with most node versions and build pipelines. Can you give me some details about your build process/node version? Because i also use it with the import syntax on all places.

**Comment by tamino-martinius** [comment]
Okay, i thought node is just using `--experimental-modules` on the module entry, which is right but not in strict mode. I added a build step to create `.mjs` files and changed the module entry to these.
Can you confirm that `v1.0.6` is working for you?

**Comment by arlac77** [comment]
Using your version 1.0.6:

When i remove the 'export *' from your index.mjs
```js
//export * from './github';
import { GitHub } from './github';
export default GitHub;
//# sourceMappingURL=index.mjs.map
```

I am able to use your module as described

```js
import GitHub from 'github-graphql-api';
``` 

as far as i understand you only can use either default or several export entries not both variants at the same time

**Comment by tamino-martinius** [comment]
Hmm `named` and `default` exports at the same time should not be an issue.

At the mdn is even example which is nearly the same: https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export#Module_Redirects

**Comment by arlac77** [comment]
Sorry You are right.
It works with your plain 1.0.6 version too

**Comment by tamino-martinius** [comment]
Great 👍thy for pointing out the issue with the mjs module package entry - need to change it on some of my other packages aswell =)
